name: learn-docker

services:
  web:
    build: .
    image: app-image
    container_name: app-container
    command: uv run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./a_core:/app/a_core
      - ./a_home:/app/a_home
      - ./static:/app/static
      - ./templates:/app/templates
      - ./manage.py:/app/manage.py
      - /app/.venv
      - venv_data:/app/venv
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres-container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  venv_data:
  postgres_data:
  redis_data:
  
