name: learn-docker

services:
  web:
    build: .
    image: app-image
    container_name: app-container
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./a_core:/app/a_core
      - ./a_home:/app/a_home
      - ./static:/app/static
      - ./templates:/app/templates
      - ./manage.py:/app/manage.py
      - /app/.venv
      - venv_data:/app/venv
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres-container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    image: app-image
    container_name: celery-container
    command: celery -A a_core worker -E -l info
    volumes:
      - ./a_core:/app/a_core
      - ./a_home:/app/a_home
      - ./static:/app/static
      - ./templates:/app/templates
      - ./manage.py:/app/manage.py
      - /app/.venv
      - venv_data:/app/venv
    depends_on:
      - web
      - redis
      - postgres

  flower:
    image: app-image
    container_name: flower-container
    command: celery -A a_core flower --basic_auth=admin:password123
    ports:
      - "5555:5555"
    depends_on:
      - redis

  beat:
    image: app-image
    container_name: beat-container
    command: celery -A a_core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./a_core:/app/a_core
      - ./a_home:/app/a_home
      - ./static:/app/static
      - ./templates:/app/templates
      - ./manage.py:/app/manage.py
      - /app/.venv
      - venv_data:/app/venv
    depends_on:
      - redis
      - web

volumes:
  venv_data:
  postgres_data:
  redis_data:
  
