name: my-docker-project

version: '3'
services:
  web:
    image: app-image-uv
    container_name: app-container-uv
    ports:
      - "8000:8000"
    volumes:
      - .:/app                    # Bind mount the current directory to /app in the container
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: