name: my-docker-project

version: '3'
services:
  web:
    image: my-docker-image
    container_name: my-docker-container 
    ports:
      - "8001:8000"
    volumes:
      - .:/app                    # Bind mount the current directory to /app in the container
