name: django-docker-starter

services:
  app:
    build: .
    image: app-image
    container_name: app-container
    command: ./entrypoint.sh
    volumes:
      - ./a_core:/app/a_core
      - ./a_home:/app/a_home
      - ./a_users:/app/a_users
      - ./templates:/app/templates
      - ./manage.py:/app/manage.py
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres
    container_name: db-container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
