name: django-docker-starter

services:
  app:
    build: .
    image: app-image
    container_name: app-container
    command: ./entrypoint.sh
    volumes:
      - ./a_core:/app/a_core
      - ./a_home:/app/a_home
      - ./a_users:/app/a_users
      - ./templates:/app/templates
      - ./manage.py:/app/manage.py
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
    depends_on:
      - db

  db:
    image: postgres
    container_name: db-container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
