[project]
name = "django-docker-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django",
    "pillow",
    "django-cleanup",
    "django-allauth",
    "django-htmx",
]
